In [7]:
import numpy as np
import pandas as pd


#Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [24]:
#Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)

print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [25]:
#Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
#Ответ: нет



In [31]:
#Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
#Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
x = np.random.randn(3, 4) 
x1 = x.reshape(1, 12)
print(x1)

[[ 0.77971659  0.67302439  0.7399664  -1.18420434 -0.13428878  0.65237921
   0.10880423  0.63600962  0.10165045  2.71956079 -1.85967972  0.41663698]]


In [32]:
#Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [35]:
#Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
#В чем разница между массивами a и b? (Ответ: массив b двумерный)
b = np.arange(20, 1, -2)
b = b.reshape(1, 10)
b


array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [58]:
#Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
#чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.
a = np.zeros((2, 2))
b = np.ones((3,2))
v = np.vstack((a, b))
v.size


10

In [63]:
#Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
#Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. 
#Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
#Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
a = np.arange(0, 12, 1)
a = a.reshape(4, 3)
at = a.transpose()
b = np.dot(a, at)
print(b)
b.shape
res = np.linalg.det(b)
res
#Ответ: определитель матрицы = 0, соответственно для матрицы b обратная матрица не существует

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


0.0

In [64]:
#Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
np.random.seed(42)

In [67]:
#Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно 
#распределенных целых чисел от 0 до 16 невключительно. 
c = np.random.randint(0, 16, 16)
c

array([ 3,  7,  7,  2,  5,  4,  1,  7, 11, 13,  5,  1, 15, 11,  4,  0])

In [93]:
#Поменяйте его форму так, чтобы получилась квадратная матрица C. 
#Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
#Вычислите определитель, ранг и обратную матрицу D_inv для D.
c = c.reshape(4, 4)
d = np.add(b, c*10)
det = np.linalg.det(d)
ra = np.linalg.matrix_rank(d)
d_inv = np.linalg.inv(d)
print(det)
print(ra)
print(d_inv)


-23404999.999999978
4
[[-0.02745824 -0.02127921 -0.00030506  0.01848067]
 [-0.00983038 -0.00115445  0.03006537 -0.01967443]
 [ 0.03091391  0.00259603 -0.0266755   0.01263576]
 [-0.00169622  0.01154454 -0.00065371 -0.00325571]]


In [94]:
#Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
#Убедитесь, что в матрице D_inv остались только нули и единицы. 
#С помощью функции numpy.where, используя матрицу D_inv в качестве маски, 
#а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  
#Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
#должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, 
#для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.
print(d_inv)
for i in range(4):
    for j in range(4):
        if d_inv[i][j] < 0:
            d_inv[i][j] = 0
        else :
            d_inv[i][j] = 1
print(d_inv)
print(b)
print(c)
e = np.where(d_inv == 1, b, c)
print(e)

[[-0.02745824 -0.02127921 -0.00030506  0.01848067]
 [-0.00983038 -0.00115445  0.03006537 -0.01967443]
 [ 0.03091391  0.00259603 -0.0266755   0.01263576]
 [-0.00169622  0.01154454 -0.00065371 -0.00325571]]
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 1. 0. 1.]
 [0. 1. 0. 0.]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 3  7  7  2]
 [ 5  4  1  7]
 [11 13  5  1]
 [15 11  4  0]]
[[  3   7   7  32]
 [  5   4  86   7]
 [ 23  86   5 212]
 [ 15 122   4   0]]
